### ISSUE TITLE
No overlay file in default cofing

### ISSUE THREAD

**Issue by a0405u** [badjeff/zmk-analog-input-driver#3]
As I understood, I should modify my board .overlay file to use this driver. I use default ZMK board so my current config contains no corne board files such as .overlay. 

Can I somehow install this as a module without touching the files of my corne? Or is it better to just copy the board files from ZMK repo to my local config and modify them? Which of them do I need to make a fully functional local copy that I can modify? Is there an example config that I can use to connect a stick to a keyboard as a mouse?

Sorry for such dumb questions.

**Comment by badjeff** [comment]
No, you need to fork and modify zmk config to load up the module. Just read the zmk doc.

You'd gather the input driver definition node in one file and then include it in .overlay file like [what I did here](https://github.com/badjeff/zmk-config/blob/1549e9d7c2ec1daed28b1b74e135e1e3b5889c18/config/boards/shields/zero36/zero36.overlay#L11).

Also, zmk pointer feature is under very active development right now. Better to ask in ZMK discord server #pointer-device channel.

**Comment by a0405u** [comment]
Ok, thank you! I'll check your config, it should help!
